# Generated by Django 6.1.1 on 2026-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "pbev",
                                "INMETRO — Programa Brasileiro de Etiquetagem Veicular",
                            ),
                            ("reference", "Perfil de referência (aproximado)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("brand", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=120)),
                ("version", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveSmallIntegerField(null=True)),
                ("search_key", models.CharField(db_index=True, max_length=400)),
                (
                    "gasoline_city",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "gasoline_highway",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "ethanol_city",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "ethanol_highway",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "diesel_city",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "diesel_highway",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
            ],
            options={
                "ordering": ["brand", "model", "version", "-year"],
            },
        ),
    ]
