# Generated by Django 6.1.1 on 2026-10-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionRunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("anp", "ANP — Levantamento de Preços de Combustíveis"),
                            ("petrobras", "Petrobras — composição de preços"),
                            ("demo", "Dados de demonstração"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(db_index=True)),
                ("written", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("anp", "ANP — Levantamento de Preços de Combustíveis"),
                            ("petrobras", "Petrobras — composição de preços"),
                            ("demo", "Dados de demonstração"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AM", "Amazonas"),
                            ("AP", "Amapá"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MG", "Minas Gerais"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MT", "Mato Grosso"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("PR", "Paraná"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("RS", "Rio Grande do Sul"),
                            ("SC", "Santa Catarina"),
                            ("SE", "Sergipe"),
                            ("SP", "São Paulo"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasolina comum"),
                            ("gasoline_premium", "Gasolina aditivada"),
                            ("ethanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("diesel_s10", "Diesel S10"),
                            ("cng", "GNV"),
                            ("lpg", "GLP (botijão 13 kg)"),
                        ],
                        max_length=24,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("average", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "minimum",
                    models.DecimalField(decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "maximum",
                    models.DecimalField(decimal_places=3, max_digits=8, null=True),
                ),
                ("stations", models.PositiveIntegerField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fuel", "state", "-period_end"],
                        name="fuel_state_period",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "state", "fuel", "period_end"),
                        name="one_report_per_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("average__gt", 0)), name="average_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start__lte", models.F("period_end"))
                        ),
                        name="period_ordered",
                    ),
                ],
            },
        ),
    ]
